# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krate < Formula
  desc ""
  homepage "https://github.com/kublet/homebrew-tools"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kublet/krate/releases/download/v0.0.3/krate_Darwin_x86_64.tar.gz"
      sha256 "ebb4ee4ce39d33f1298a7102cab1dab6e1604984af2ab4dd512c8772eeeff1f5"

      def install
        bin.install "krate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kublet/krate/releases/download/v0.0.3/krate_Darwin_arm64.tar.gz"
      sha256 "d9b34ba8ec043fcece074d31979e5bcdb0b567c103a9c8b808e44315a34169aa"

      def install
        bin.install "krate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kublet/krate/releases/download/v0.0.3/krate_Linux_x86_64.tar.gz"
      sha256 "b39c4405e1843d4020c870102c09452639780ae0406e5298972bea9b31b5f184"

      def install
        bin.install "krate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kublet/krate/releases/download/v0.0.3/krate_Linux_arm64.tar.gz"
      sha256 "ca8ea5f629141519d428a23cbc090b1a054e8e4930c847b52f134e7e6b89a43a"

      def install
        bin.install "krate"
      end
    end
  end
end
