# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krate < Formula
  desc ""
  homepage "https://github.com/kublet/homebrew-tools"
  version "0.0.11"

  on_macos do
    on_intel do
      url "https://github.com/kublet/krate/releases/download/v0.0.11/krate_Darwin_x86_64.tar.gz"
      sha256 "ad6406e20c08408b98a59488741cfc008236f162b8f4c7f002d93442624983b0"

      def install
        bin.install "krate"
      end
    end
    on_arm do
      url "https://github.com/kublet/krate/releases/download/v0.0.11/krate_Darwin_arm64.tar.gz"
      sha256 "3afebc3020991e92c48888ed6150ab854490bc17ce1151b743d6e9b6900221a6"

      def install
        bin.install "krate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_x86_64.tar.gz"
        sha256 "3bf051c0680ffc51933e1b27fc36b413fbf90678dc156003c9c5b41ee64c7b86"

        def install
          bin.install "krate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_arm64.tar.gz"
        sha256 "17e21dec5ce31ef6d5cbec249b28b452fa7709cdb7b8f4a29b3b52651b175c9b"

        def install
          bin.install "krate"
        end
      end
    end
  end
end
